name: Get latest transparentpath version
on:
  schedule:
    - cron:  "*/60 * * * *"
  workflow_dispatch:
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip index versions transparentpath | grep -Po '(?<=\().*(?=\))'
